# 标量

包含一个数值的叫标量（scalar）。标量由只有一个元素的张量表示：

In [1]:
import torch

x = torch.tensor(3.0)
y = torch.tensor(2.0)

x + y,x * y,x / y,x ** y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

# 向量

将向量视为标量值组成的列表。 我们将这些标量值称为向量的元素（element）或分量（component）。通过一维张量处理向量。一般来说，张量可以具有任意长度，取决于机器的内存限制，可以使用下标来引用向量的任一元素。

![](./img/array.png)

In [7]:
x = torch.arange(4)
x,x[3]

(tensor([0, 1, 2, 3]), tensor(3))

## 长度，维度和形状
 
向量的长度通常称为向量的维度，可以通过调用 Python 的内置 len()函数来访问张量的长度。当用张量表示一个向量（只有一个轴）时，我们也可以通过.shape属性访问向量的长度。 形状（shape）是一个元素组，列出了张量沿每个轴的长度（维数）。 对于只有一个轴的张量，形状只有一个元素:


In [8]:
len(x),x.shape

(4, torch.Size([4]))

# 矩阵

正如向量将标量从零阶推广到一阶，矩阵将向量从一阶推广到二阶。

![](./img/matrix.png)

In [10]:
A = torch.arange(20).reshape(5, 4)
A,A[-1],A[2][3]

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]),
 tensor([16, 17, 18, 19]),
 tensor(11))

当我们交换矩阵的行和列时，结果称为矩阵的转置（transpose）：

In [11]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

作为方阵的一种特殊类型，对称矩阵（symmetric matrix）$\mathbf{A}$ 等于其转置：$\mathbf{A}=\mathbf{A}^{\top}$，定义一个对称矩阵:

In [15]:
B = torch.tensor([[1,2,3],[2,0,4],[3,4,5]])

B,B == B.T

(tensor([[1, 2, 3],
         [2, 0, 4],
         [3, 4, 5]]),
 tensor([[True, True, True],
         [True, True, True],
         [True, True, True]]))

# 张量


就像向量是标量的推广，矩阵是向量的推广一样，我们可以构建具有更多轴的数据结构。 张量为我们提供了描述具有任意数量轴的 n 维数组的通用方法:

In [18]:
X = torch.arange(24).reshape(2,3,4)

X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

## 张量算法的基本性质

给定具有相同形状的任意两个张量，任何按元素二元运算的结果都将是相同形状的张量:

In [20]:
A = torch.arange(20,dtype=torch.float32).reshape(5,4)
B = A.clone()
A,A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

将张量乘以或加上一个标量不会改变张量的形状，其中张量的每个元素都将与标量相加或相乘：

In [21]:
a = 2
X = torch.arange(24).reshape(2,3,4)
a + X,(a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

## 降维

计算张量元素的和：

In [22]:
x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

默认情况下，调用求和函数会沿所有的轴降低张量的维度，使它变为一个标量。 我们还可以指定张量沿哪一个轴来通过求和降低维度。 以矩阵为例，为了通过求和所有行的元素来降维（轴0），我们可以在调用函数时指定 axis=0。 由于输入矩阵沿0轴降维以生成输出向量，因此输入轴0的维数在输出形状中消失：

In [27]:
A = torch.arange(20,dtype=torch.float32).reshape(5,4)
A_sum_axis0 = A.sum(axis=0)
A,A_sum_axis0,A_sum_axis0.shape

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([40., 45., 50., 55.]),
 torch.Size([4]))

指定 axis=1 将通过汇总所有列的元素降维（轴1）。因此，输入轴1的维数在输出形状中消失：

In [29]:
A = torch.arange(20,dtype=torch.float32).reshape(5,4)
A_sum_axis1 = A.sum(axis=1)
A,A_sum_axis1,A_sum_axis1.shape

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([ 6., 22., 38., 54., 70.]),
 torch.Size([5]))

沿着行和列对矩阵求和，等价于对矩阵的所有元素进行求和：

In [30]:
A.sum(axis=[0, 1])  # A.sum()

tensor(190.)

调用 mean 函数可以求平均值：

In [31]:
A.mean(),A.sum()/A.numel(),A.mean(axis=0),A.sum(axis=0)/A.shape[0]

(tensor(9.5000),
 tensor(9.5000),
 tensor([ 8.,  9., 10., 11.]),
 tensor([ 8.,  9., 10., 11.]))

有时在调用函数来计算总和或均值时保持轴数不变会很有用：


In [34]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A,A/sum_A

(tensor([[ 6.],
         [22.],
         [38.],
         [54.],
         [70.]]),
 tensor([[0.0000, 0.1667, 0.3333, 0.5000],
         [0.1818, 0.2273, 0.2727, 0.3182],
         [0.2105, 0.2368, 0.2632, 0.2895],
         [0.2222, 0.2407, 0.2593, 0.2778],
         [0.2286, 0.2429, 0.2571, 0.2714]]))

# 点积

 给定两个向量：$\mathbf{x}, \mathbf{y} \in \mathbb{R}^{d}$，它们的点积（dot product）：$\mathbf{x}^{\top} \mathbf{y}$，或者记为：$\langle\mathbf{x}, \mathbf{y}\rangle$，相同位置的按元素乘积的和：$\mathbf{x}^{\top} \mathbf{y}=\sum_{i=1}^{d} x_{i} y_{i}$:

In [35]:
y = torch.ones(4, dtype = torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))